core/java/android/app/ActivityManager.java, core/java/android/app/Instrumentation.java, services/core/java/com/android/server/am/ActivityStarter.java
When an app launches a protected app, it crashes because the intent result is
START_NOT_CURRENT_USER_ACTIVITY instead of START_SUCCESS, add a new special case
for protected app intents
Ticket: LINN-18
Change-Id: I9736829117382e44dc42fb79c8e1902a55625a56
Signed-off-by: Joey Rizzoli <joey@lineageos.org>
=> base: instrumentation: fix protected apps intents

core/res/res/values/cm_symbols.xml, core/res/res/values/config.xml, packages/SystemUI/src/com/android/systemui/classifier/HumanInteractionClassifier.java
On some devices HumaInteractionClassifier is more of a nuisance than a
useful feature by making the screen hard to unlock at random. Add a
config that allows to define the default state of HIC, which currently
can only be disabled running the following command:
settings put global HIC_enable 0
Change-Id: I3ad85aff08fe209a21f1eae8a8719c089ed7aa28
=> SystemUI: Add config to disable HumanInteractionClassifier

packages/SystemUI/src/com/android/systemui/statusbar/phone/NotificationPanelView.java
With Android N this feature became less relevant since a subset of
the toggles is available without fully expanding the notification
panel. This gives better access to the notifications with almost no
functionality loss.
Change-Id: Idb66472b77e60f4ae753c5dd00f6588566cc3c63
=> Disable quick pulldown by default

packages/SystemUI/src/com/android/systemui/volume/VolumeDialog.java
Fixes not disappearing cast pickers
* Commit 568585b introduced a new LinearLayout for the volume rows
* Remove unused booleans
Change-Id: I0660d10872cc1098fdd67b618a20ea0f8e926e68
=> VolumeDialog: Fix mismerge

core/java/android/hardware/Camera.java, core/java/android/hardware/camera2/CameraManager.java
Secondary cameras work fine on our platform; there is no reason to
disable them by default. Convert the opt-in package list to be opt-out
to allow disabling packages with known incompatibilities with the dual
camera setup (looking at you Snapchat)
Change-Id: Ie80434c3db160a424c346ff09b30191147a32b32
=> camera: Make secondary camera package list opt out

services/usage/java/com/android/server/usage/UsageStatsDatabase.java, services/usage/java/com/android/server/usage/UsageStatsXml.java, services/usage/java/com/android/server/usage/UsageStatsXmlV1.java, services/usage/java/com/android/server/usage/UserUsageStatsService.java
The resolver calls UsageStatsManager.queryUsageStats() to get package
usage information. This causes all XMLs of the selected bucket to be
read, which can be of significant size. However, the majority of that
size is due to usage event information, which queryUsageStats() isn't
interested in, so it'll parse a lot of data just to throw it away later
on.
Solution: Don't parse the portions of the XMLs we aren't interested in.
Change-Id: Ia2595201c9fcceab2778618fd0cccfb19ad4ed8d
=> Fix intermittent slowness in resolver activity towards end of day.

core/java/android/provider/Settings.java, core/java/com/android/internal/widget/LockPatternUtils.java, services/core/java/com/android/server/LockSettingsService.java
This reverts commit 9d37d587aa2285513957fb204ce98856eafe797d.
Separated encryption password implementation is currently not so well implemented
and it exposes some additional security issues
Change-Id: I290491d6db445785aa750ac35b06e6524659af9f
Signed-off-by: Joey Rizzoli <joey@lineageos.org>
=> Revert "[1/2] base: support separate encryption/lockscreen passwords"

services/core/jni/com_android_server_power_PowerManagerService.cpp
We changed the behavior of setPowerHint() so that our HALs could
easily handle the POWER_HINT_SET_PROFILE hint. However, this silently
broke the compatibility with AOSP. Restore the original code and
handle differently only our custom hints.
Change-Id: Ifeaae04fff8cafb4df3becc87dfdbeae48006ee3
=> PowerManager: Bring back the compatibility with AOSP

packages/Keyguard/res/values/strings.xml, packages/Keyguard/src/com/android/keyguard/KeyguardSimPinView.java
Causes format string parameter mismatches with non-English locales.
This reverts commit 0aae1f69b38fbf1b12f63da770adbaab5b3c855d.
Change-Id: I0422de74fad5acdac5a0201430d551fb4cf7cbc6
=> Revert "SystemUI: Add SlotId for MultiSim"

core/java/android/view/WindowManagerPolicy.java, services/core/java/com/android/server/policy/PhoneWindowManager.java, services/core/java/com/android/server/wm/WindowAnimator.java
Showing the content of the screen allows to use the device
without unlocking it first. Don't alter the way windows are hidden
to prevent any interaction.
BUGBASH-268
Change-Id: Id1d7ba4c51b62ea6b514ece9ac03ab271e63df84
=> Show lockscreen wallpaper when blur effect is enabled

core/res/res/values/cm_symbols.xml, core/res/res/values/config.xml, services/core/java/com/android/server/fingerprint/FingerprintService.java
* Some fingerprint hardware hals might not notify userspace in time
in some scenarios when successful authentication cancel is performed.
* This is observed for example in some devices that have power and/or home
buttons merged with fingerprint sensor, but not limited to such cases.
* Add a opt-in configuration to enable client authentication cancel from
fingerprint service when successful.
* This addresses originally an issue where requesting fingerprint to be
disabled and then enabled will wait till cancelling timeout before changing
fingerprint sensor state and start authenticating again.
Change-Id: I6a6795fbb795f0c6a4ff8ad27ac807e2f744c2d9
Signed-off-by: Carlo Savignano <carlosavignano@aospa.co>
=> fingerprint: notify client when cancelling succeeded

packages/SystemUI/src/com/android/systemui/statusbar/phone/KeyguardBottomAreaView.java
In the current implementation only the left target is being properly
updated via 'updateLeftAffordance'. Implement 'updateRightAffordance'
to handle the right target in a similar fashion.
This fixes (1) a rare scenario where the right target would be color-
ed black instead of gray and (2) the launch animation background for
custom targets not adopting the icon color of the selected app.
BUGBASH-353
BUGBASH-356
Change-Id: I556fc7316c3b646bf004b4f0a510fbc3736b2bd8
=> SystemUI: Misc fixes for right (custom) lockscreen shortcuts

packages/SystemUI/src/com/android/systemui/qs/QSTile.java
handleDestroy() calls setListening(false) unconditionally. This
causes an error if no listener was never added. Check if we added
a listener and then try to remove it.
Change-Id: Iefe8aacbe87ba1c2c19c9e77cf132fc7c84798f9
=> QS: Remove listeners only if added

services/core/java/com/android/server/pm/UserManagerService.java
We can use the command 'adb shell pm create-user --profileOf -10000
--managed TestProfile_12345678' to reproduce the problem.
Change-Id: I004ef8dd2aee4e911c292ddf85422a22ecbecd15
=> Fixed NPE in canAddMoreManagedProfiles

services/core/java/com/android/server/fingerprint/FingerprintService.java
bcc100a has added support for this feature, but the NULL checks
weren't complete, only "handleAcquired" was checking if PerformanceStats
was supported before calling the API.
Extend the NULL checks to "handleAuthenticated" and "handleFailedAttempt"
calls as well.
Change-Id: I3cc9b35ea6b81dc0c503b9feab940873b344323e
Signed-off-by: Ícaro Hoff <icarohoff@gmail.com>
=> fingerprint: handle PerformanceStats NULL pointers

services/core/java/com/android/server/location/GnssLocationProvider.java
SystemClock.elapsedRealtime() returns milliseconds since boot, and
is less vulnerable to system time issue.
Change-Id: I01c2c1205c4306c6d8ce62875ff1295001ed8491
CRs-fixed: 2015708
=> Use SystemClock.elapsedRealtime() to calc TTFF

core/java/android/provider/Settings.java
With some mobile network operators, the presentation indicator of
outgoing calls is always set to either "unknown" or "restricted".
As consequence, the dialed number doesn't show up in clear in the
call history. Allow to ignore the presentation indicator of outgoing
calls to never hide the dialed numbers.
Change-Id: Ia40de2ce40fee5068f82abd69595b34d2596caae
=> Allow to ignore presentation indicator of outgoing calls [1/3]

packages/Keyguard/src/com/android/keyguard/KeyguardUpdateMonitor.java
* This patch affects devices that disable fingerprint
wake-and-unlock via config_fingerprintWakeAndUnlock,
and is mainly for fp scanners in the power button
* Don't listen to fingerprints when going to sleep
to avoid a wakeup being triggered after pressing
the power button to turn the screen off
* Fixes the following scenario:
- Turn device on with not registered finger
- Check time (or something on lock screen)
- Use registered finger to turn off device,
and leave finger on the scanner
- Device screen turns off
- Device wakes up at home screen
Change-Id: Ia40a6a763420cd716796515ddb9b816232218dc0
=> Keyguard: Change fingerprint listening behavior

services/core/java/com/android/server/location/GnssLocationProvider.java
Since commit b2b4489760230258d23f72f8f8dd643b09cd5b04
("Use SystemClock.elapsedRealtime() to calc TTFF") mLastFixTime
stores the time since boot rather than the current real time.
REGRESSION-1032
Change-Id: I39474a66c6d7dbd9ca0ff50a5a1b9c06007725c4
=> Don't disable the GPS prematurely

services/core/java/com/android/server/notification/ZenModeHelper.java
mAllowLights is false by default, so if zen_mode is set to
ZEN_MODE_OFF, LED notifications will be suppressed. Ensure
mAllowLights is true when zen_mode is ZEN_MODE_OFF.
BUGBASH-1259
Change-Id: I979a4d9cfee4ee77c0cd3b9d6338d55961183eb7
=> ZenModeHelper: Allow lights by default

packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBar.java
Enabling the setting did not work because the SYSTEMUI_BURNIN_PROTECTION
string had wrong prefix and was not registered as tunable.
Change-Id: I6a99a7616b2e980aa8d4dfd86ba82351508825b2
=> SystemUI: fix enabling burnIn protection

packages/SystemUI/src/com/android/systemui/qs/tiles/LiveDisplayTile.java
* During boot, with LineageHW not yet initialized there is no way to
check the current LiveDisplay mode. In such cases, fallback to AUTO.
Change-Id: Ifc004c86dfd68f73b8a362a1c833cbc3e7397811
=> LiveDisplayTile: Avoid NPE during boot up phase

core/java/android/hardware/Camera.java, core/java/android/hardware/camera2/CameraManager.java, core/jni/android_hardware_Camera.cpp
Issue:
3rd party apk cannot handle additional aux camera and may cause crash,
Mono camera doesnt support all capabilities of HAL3 causing CTS issue.
Fix:
1. Expose aux camera to apps present in the whitelist
2. ignore the availabe/unavailable status update for aux camera
3. returning exception for open request for bad cameraid
Change-Id: I15910154c6df205e6d4e00bfad30a00c9e3d5bee
CRs-Fixed: 1086937
=> Camera: Expose Aux camera to apps present in the whitelist

services/core/java/com/android/server/pm/PackageManagerService.java
* mPlatformPackage is not set until later in the package parsing
process. Avoid the NPE instead of catching it, as it leaves
packages unparsed.
Change-Id: Ib88a7e4e3f723288ad435d79b1b68d6d3fcb48c2
=> PackageManager: Don't dereference mPlatfromPackage until available

packages/SystemUI/src/com/android/systemui/keyguard/KeyguardViewMediator.java
Properly dismiss keyguard on boot if the current profile has it
disabled, otherwise we will just show a black screen with just the
status bar and a navbar with only the back button.
BUGBASH-87
Change-Id: I14ed10ae9db40c32be22c1fb43f8a1719787d91b
=> SystemUI: Dismiss keyguard on boot if disabled by current profile

packages/SystemUI/src/com/android/systemui/globalactions/GlobalActionsDialog.java, services/core/java/com/android/server/policy/PhoneWindowManager.java
* A partial screenshot shouldn't timeout when the user might still be
adjusting the rectangle
BUGBASH-1500
Change-Id: Ifb06173dc712667db3bfb3c6f945b9bddb2a85fa
=> PhoneWindowManager: Don't timeout when taking a partial screenshot

packages/SystemUI/res/values-tr/strings.xml
When the device is 100% charged, the "Charged" string
on the lock screen is translated into Turkish;
"Ödeme alındı", English equivalent; "Payment received".
So when the device is fully charged, it displays
"Payment received" in English on the screen.
Change-Id: I1de8e8b5500ce34635e71b9bdcdfea8fe7777fbe
=> SystemUI: Fix Turkish AOSP translation error

telephony/java/android/telephony/CarrierConfigManager.java
Carriers want to hide signal strength in Sim Status.
Bug: 69730732
Test: Add different values for two carriers in vendor.xml
and see them change when swapping sim card
Change-Id: I155c8f619a451edab85cf6422cef73e8e1686629
=> Make it possible to hide signal strength via Carrier Config

packages/SystemUI/src/com/android/systemui/screenshot/GlobalScreenshot.java
When device is locked, current implementation will append the current
app name to file when taking screenshot. This causes information leaks.
To prevent this, we check for isKeyGuardLocked() and fall back not to
append the app name when taking screenshot on lockscreen.
Change-Id: I04498faf51986e1a3723a32befd97d29e1f3fe58
=> SystemUI: Don't append app name to file on lockscreen

packages/SystemUI/src/com/android/systemui/statusbar/notification/HybridGroupManager.java, packages/SystemUI/src/com/android/systemui/statusbar/stack/NotificationChildrenContainer.java
When density or font size is updated, overflow number view's size
was not updated.
Test: Group notification with overflow number existing
> Change density or font size > Check overflow number view's size
Change-Id: I6f464b12f83b954f7fbfdd5d64153598b5407e08
=> Update text size of overflow number view

packages/SystemUI/src/com/android/systemui/qs/QSPanel.java
Alignment of brightness mirror dialog was not exatly same as the
QS brightness dialog, which produced a visual glitch of slider
thumb shifting whenever we change brightness.
This is solved by dynamically handling the visibility of
mirror brightness icon, gone when brightness icon is off and
invisible when brightness icon is on, so that both mirror and
QS slider are equally aligned.
Change-Id: Ifb85643db669ee8d7473d3c48e7e4733428a77d6
=> SystemUI: Fix alignment glitch with brightness mirror

services/core/java/com/android/server/am/ActivityManagerService.java, services/core/java/com/android/server/am/ActivityRecord.java
When an app target pre-O releases, the default max aspect ratio
is 1.86:1 which leads to ugly black areas on devices that have
screens with higher aspect ratio (for example Galaxy S8/S9).
This change adds an option to allow users to change aspect ratio
for pre-O apps to full screen aspect ratio.
Change-Id: I41d5408841593a12443be885e11959bffaebb67b
=> Add an option to force pre-O apps to use full screen aspect ratio

core/java/com/android/internal/widget/ILockSettings.aidl, core/java/com/android/internal/widget/LockPatternUtils.java, packages/SystemUI/src/com/android/keyguard/KeyguardAbsKeyInputView.java, packages/SystemUI/src/com/android/keyguard/KeyguardPatternView.java, services/core/java/com/android/server/StorageManagerService.java, services/core/java/com/android/server/locksettings/LockSettingsService.java
Port password retention feature for HW FDE.
This patch also include these changes:
- Fix clearing of retained password
- keyguard: Fix password doesnot sanitize after verification
- LockSettings: fix the get password issue during boot up
- frameworks/base: Fix pattern update issue
Change-Id: I2def56b14c10229b72feccd1c97b281cad65f282
=> frameworks: base: Port password retention feature

services/core/java/com/android/server/policy/PhoneWindowManager.java
This allows long press power button for torch and long press
volume buttons for track skip to work during ambient display.
sam3000/razorloves: partial pick from:
Author: ezio84 <brabus84@gmail.com>
Date:   Fri Feb 2 01:24:34 2018 -0500
base: Support binding the power button to flashlight
Thanks to beanstown106 for the initial longpress action calls in
PhoneWindowManager (improved by lineage guys)
[cut]
Allow torch action also on ambient display
Change-Id: I12da044f86c7b625872607529cf8524615cf576b
Author: ezio84 <brabus84@gmail.com>
Date:   Sun, 7 Jan 2018 21:24:53 +0100
Fix volume rocker skip track on Ambient Display and Lift to Wake
we need to check if dream service is dozing before checking
keyguard status
Change-Id: Ic3a6c830496188bb6edf27043cd24eb2d553bb82
Change-Id: …
=> PhoneWindowManager: Allow torch and track skip during ambient display

packages/SystemUI/src/com/android/systemui/qs/tiles/CellularTile.java
* We recently enabled dualTarget for CellularTile which allowed us
to toggle mobile data without unlocking device. Moving showDetail
call to postQSRunnableDismissingKeyguard when the device is locked
fixes this issue.
Change-Id: I16dc766166a33a309a2fc945e81fa15b5d194196
=> SystemUI: CellularTile: Don't call showDetail() when device is locked

core/java/com/android/internal/app/ChooserActivity.java
Limit target packages and services query to reduce lag
when opening the share menu
Change-Id: I00179a87132d5d186b9482e0b6424eae0d175fbd
=> base: limit direct share targets to reduce lag

media/java/android/media/MediaFile.java, services/core/java/com/android/server/storage/FileCollector.java
The codec and container format are already supported, but not in that
combination. Simply add the file extension as a type of Ogg file (which
it is).
Change-Id: Ia9134a8d1205f73da12f579b3ad62367b2b8d88e
See: https://issuetracker.google.com/issues/37054258
=> Add support for the .opus file format

packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarView.java
* On clean installations this would end up being
initialized to invalid value. Changing this
into v != null && v != 0 check, which matches
other SystemUI tuning checks fixes this issue.
Change-Id: I9b0e000f15a39f71788259e4db962d04b7f8f0c9
=> SystemUI: Fix default mShowDpadArrowKeys value

services/core/java/com/android/server/am/UserController.java, services/core/java/com/android/server/pm/UserManagerService.java
*) We changed PackageManagerService to use Build.DATE instead of
Build.FINGERPRINT to detect upgrade.  Do the same for
UserManagerService.
*) Affects generation of preboot intent and app data migration.
Change-Id: I56887b7ca842afdcf3cf84b27b4c04667cf43307
=> fw/b UserManagerService: Use ro.build.date to signal upgrades

packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_0.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_1.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_2.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_3.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_4.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_5.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_6.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_7.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_8.xml, packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_9.xml, packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBarPolicy.java
* Somewhat inspired by change committed by Gavin Ni <gisngy@gmail.com>
back in cm-13.0 days (see commit 88e7a6c). Since then completely
rewritten using BluetoothDevice API introduced in Oreo, with new
drawables meant to be used with 0-9 battery level range.
Change-Id: I6179bfd41e033591534e8cf3c6adc98ce715a13d
=> SystemUI: Show bluetooth battery level when available

packages/SystemUI/LineageManifest.xml, packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBar.java
Author: Joey <joey@lineageos.org>
Date:   Thu Dec 28 20:28:01 2017 +0100
systemui: introduce berry styles
Change-Id: I61d0861112ae9b25db20b8d5e57d2a5f8a26b833
Signed-off-by: Harry Youd <harry@harryyoud.co.uk>
Author: Joey <joey@lineageos.org>
Date:   Fri Mar 9 22:49:01 2018 +0100
base: update UiManager's night mode according to berry state
Change-Id: I2eb43f1760e95246b81e487f420f42550ef3ddcd
Author: Joey <joey@lineageos.org>
Date:   Thu Jul 5 21:14:01 2018 +0200
systemUi: styles: support more dark overlays
Change-Id: I4fafa2b1e342608e2690c3dda7cb06aaf88247ba
Change-Id: Ia75685e4f44ecd22e781a32d06a2a5c885b559ed
=> SystemUI: Berry styles

packages/SystemUI/res/values-sw600dp/dimens.xml
Change-Id: I047453c169854636d9e179d4678b94c7724bb854
=> SystemUI: Fix too big spacing between QS icons in landscape on sw600dp

Android.bp, core/res/AndroidManifest.xml, telephony/java/com/android/internal/telephony/ISmsSecurityAgent.aidl, telephony/java/com/android/internal/telephony/ISmsSecurityService.aidl, telephony/java/com/android/internal/telephony/SmsAuthorizationRequest.aidl, telephony/java/com/android/internal/telephony/SmsAuthorizationRequest.java
- Add the APIs required to register an authorization agent in order
to allow/reject outgoing SMS messages and the core service that
implements the sms security model.
Change-Id: Ic7c35aef6acb50fde1fc52d20cea6547bc546aab
=> Add auth framework for outgoing SMS messages.

core/jni/android_util_Binder.cpp
* dumpProxyDebugInfo doesn't have a return value, so it should be
invoked via CallStaticVoidMethod instead of CallStaticObjectMethod.
Change-Id: Ie4c497f69b371ec3d55e7736827f73142d14a5b4
=> Binder: Fix improper JNI call for dumpProxyDebugInfo

packages/SettingsLib/src/com/android/settingslib/wifi/WifiStatusTracker.java, packages/SettingsLib/src/com/android/settingslib/wifi/WifiTracker.java, packages/SystemUI/src/com/android/systemui/statusbar/policy/HotspotControllerImpl.java, packages/SystemUI/src/com/android/systemui/statusbar/policy/WifiSignalController.java
When sets pin lock and reboot phone, SystemUI could not
get WifiManager when creates WifiTracker, then NullPointerException
will happen.So add null pointer checking and avoid
creating WifiTracker for encrypted device to fix this exception.
Bug: 109588864
Test: manual,set pin lock and reboot phone,systemUI can restart normally.
Change-Id: I9bf5d52fa0b1efd99d1f32686f12b5c99765b0c2
=> Fix NPE when creates wifi tracker

services/core/java/com/android/server/am/ActiveServices.java, services/core/java/com/android/server/am/ActivityManagerConstants.java, services/core/java/com/android/server/am/ActivityManagerService.java, services/core/java/com/android/server/am/ActivityRecord.java, services/core/java/com/android/server/am/ActivityStack.java
The following optimizations are squashed in this change.
1. Enable Aggressive trim settings.
This change will enable aggressive trim settings for targets
up to 1GB. The change can be turned on/off from system properties.
By default, the properties are set for targets up to 1GB
Changes spread in to : ActivityManagerConstants.java
2. Propagate B-services to higher adj.
Depending on the inactivity of a service, move the B-services to
highest adj 906. Under memory pressure, these services will
be killed first ahead of cached apps which results in better
concurrency numbers with bg apps. Inactivity time and minumum
no of services to be maintained are configurable as system properties.
Improves concurrency.
Changes spread in to : ActivityManagerService.java
3. Postpone service restart during …
=> Performance: Memory Optimizations.

services/core/java/com/android/server/InputMethodManagerService.java
Doing so allows us to keep track of user changes and restore
preferences.
This commit is squash of the following commits from CM 13.0:
7348be747940afe7c3ec6a2b133b5473bc18573a Move high touch sensitivity and hovering to InputService
f9a9d50491dc583ea568a4f12e57a2f97b9baacb InputMethodManager : Move registration to systemReady
Change-Id: I5a6af73129acefa6530ceb3f73cc4cd83a19a676
Ticket-Id: CYNGNOS-1166
=> Move high touch sensitivity and hovering to InputService

packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarSignalPolicy.java
* equals and copyTo should include all MobileIconState properties
* therefore, add the newly introduced boolean, provisioned
Change-Id: Ic810bbe7538506612f86695ce520e8b9542bc634
=> StatusBarSignalPolicy: Fix missing provisioned in equals and copyTo

packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBar.java
to replicate: boot with navbar enabled, then disable navbar, then switch
the screen off, then unlock with fingeprint or power button
java.lang.IllegalArgumentException: View=com.android.systemui.statusbar.phone.NavigationBarFrame{e0f4d97 G.E...... ......ID 0,0-1080,129 #7f0a01c4 app:id/navigation_bar_frame} not attached to window manager
Change-Id: I5ae631c129af28615d26754848915e351970e422
=> Fix SystemUI FC after disabling navbar and unlocking the phone

services/core/java/com/android/server/audio/AudioService.java
* Stop turning on the audio hardware and playing silence.
* Kind of annoying with certain types of Bluetooth headphones
that don't actually play silence very well (hissssssssss).
Not to mention power usage.
Change-Id: I6985db8710f8b0f61619ac57e8efb9e4e01cc31a
(cherry picked from commit 0e8a502ff119d285fdbbf521c45213b0b42b3d6f)
=> audio: Don't play sound effects if stream is muted

packages/SystemUI/src/com/android/systemui/recents/views/grid/TaskGridLayoutAlgorithm.java
* SystemUI itself does not limit number of tasks to be shown in grid
after fb44d212f267074a305eb34fa064b6d6904aa3ef, and we have to handle
more than 8 tasks in the task stack.
* Since the grid layout algorithm is prepared for only 8 tasks, we just
drop any task out of this limit, i.e. only tasks with taskIndex =
[max(0, taskCount-8), taskCount) will be shown.
Change-Id: I8715666397bfe2067735daaaabf2cae1f2600f43
=> SystemUI: Make recents grid view accept more than 8 tasks

services/core/java/com/android/server/policy/PhoneWindowManager.java
* This addresses following issues where screen gets
turned back off after turning it on:
- User has screen peek disabled and presses KEY_FOCUS
while their device is locked and screen is off.
- User has screen peek enabled and presses KEY_FOCUS
while their device is unlocked and screen is on
then locks their device.
Change-Id: I92abc3c54747de3cc480ccd748885d80ba4a343a
=> PhoneWindowManager: Fix screen peek KEY_FOCUS handling

packages/SystemUI/LineageManifest.xml, packages/SystemUI/res/values/cm_strings.xml, packages/SystemUI/src/com/android/systemui/statusbar/phone/KeyguardBottomAreaView.java, packages/SystemUI/src/com/android/systemui/statusbar/phone/NotificationPanelView.java, packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBar.java, packages/SystemUI/src/com/android/systemui/tuner/LockscreenFragment.java, packages/SystemUI/src/com/android/systemui/tuner/ShortcutPicker.java, packages/SystemUI/src/com/android/systemui/tuner/TunerActivity.java
* Enables us to change lockscreen shortcuts, but they will be disabled as default.
(Leaving SystemUI/config.xml as it is makes this possible.)
* Adds Voice Assist and Camera shortcuts to tuner and replaces "None" shortcut
with real "None". Until now, "None" was either "None" or default shortcut, depending
on "config_keyguardShowBlablaAffordance".
* It will be located under Settings > Security & Location > Lock screen preferences
Change-Id: Ibb107e550ff492219fb6fedd63f8fc8ee89753a9
Signed-off-by: eray orçunus <erayorcunus@gmail.com>
=> SystemUI: Bring back lockscreen tuner (1/2)

core/java/com/android/internal/content/FileSystemProvider.java
ExternalStorageProvider always throw exception when renameDocument
because it will check file exist when getFileForDocId. However,
beforeVisibleFile is not exist after rename, it will throw
exception. Fix it by put getting beforeVisibleFile before rename.
Test: manual test rename in DocumentsUI
Test: atest RenameActualProviderUiTest
Fix: 113302685
Fix: 115304092
Change-Id: I45d60d2f940e3dbc2b121f7cd28acc3c2d085ec4
Merged-In: I45d60d2f940e3dbc2b121f7cd28acc3c2d085ec4
=> Fix ExternalStorageProvider always throw exception when rename

media/java/android/media/RingtoneManager.java
When changing the notification sound for some apps with app-provided sounds,
the notification URI doesn't have a numerical ID.
For example, Outlook's email notification URI has the id 'new_email'
Test: m, outlook doesn't crash anymore, test google calendar
Change-Id: Ibf0c6f2f13e1c76ce02784165b97b92e8f7e432c
=> RingtoneManager: Don't crash if the ringtone doesn't have a numerical ID

services/core/java/com/android/server/BatteryService.java
If the battery warning boundary is changed and the new boundary is
higher than the current battery level, send the battery low intent too.
Test: manual: inspection (with different boundary level changes)
Change-Id: Ic8b7ebd4052bb757e35ed4e904ea6bddcb23a7ac
=> Send battery low intent when battery warning boundary changed

packages/SystemUI/res-keyguard/values/lineage_dimens.xml, packages/SystemUI/src/com/android/keyguard/KeyguardSecurityContainer.java, packages/SystemUI/src/com/android/systemui/biometrics/FODCircleView.java
Also allow devices to overlay the minimum bottom padding of the
keyguard security container so that they may shift the pattern/pin input
and the emergency call button up until the FOD icon does not obscure the
view.
Change-Id: Ie9652afc0d105199bf1e660221c82266ac8cf30a
=> FODCircleView: Show while bouncer is requesting Pattern or PIN

packages/SystemUI/src/com/android/systemui/qs/QSDetail.java
* Commit eff2c740e55668a4fdf427e64a8970a751830991 introduced some padding
in case of an existing corner cutout (e.g. a camera in the corner of a
display), so applies the size of the cutout as padding left/right
* it tries to keep top/bottom padding as-is by calling
get[Top|Bottom]Padding while re-applying start and end paddings to
restore the case with corner padding (e.g. after testing from developer
settings) but fails to do so by calling it on the current view instead
of the one of interest
* Fix that by getting the actual top/bottom paddings from the relevant
header view
* Also fix the right padding - it should be qs_panel_padding according
to the layout file
Test: QS Detail looks like before r37 merge
Test: Activate corner cutout and see if the inset applies properly,
then deactivate …
=> SystemUI: Fix QS Detail Header

data/etc/privapp-permissions-platform.xml
It's needed because when we broadcast ACTION_SIM_SLOT_STATUS_CHANGED
we want to allow the receiving app to start an activity from the
background.
The app already has it implicitly, since it has the same shared UID as
com.android.stk which has the permission for unrelated reasons. Making
it explicit makes it less likely it will lose the permission
accidentally re-introducing a subtly bug.
Bug: 132691768
Test: Builds
Change-Id: I85669423e628b4534a3f28efd17947ca2481454e
Merged-In: I85669423e628b4534a3f28efd17947ca2481454e
=> Explicitly grant START_ACTIVITIES_FROM_BACKGROUND to com.android.phone.

core/java/android/bluetooth/le/AdvertiseData.java
Use case:
Open any app that performs advertising.
Expected result:
BLE should Start advertisement.
Observed result :
Observed force close in BA App.
Fix:
set zero into parcel if transport
discovery data is empty.
Test: BLE Start advertisement successes after performing above use case.
CRs-Fixed: 2304532
Change-Id: Ica730f8d22367864308412621a8d87e625198bec
=> BLE: Fix NPE during start advertising

core/java/com/android/internal/widget/PointerLocationView.java
When drawing a point, it should be used the same index for coordinates and state.
Test: make
Signed-off-by: xuejianbao <xuejianbao@xiaomi.com>
Change-Id: I6d66e52b029d7b08663f62ab46125230b7f9a7c5
=> Fix color mismatch of pointers

core/jni/com_android_internal_os_Zygote.cpp
This CL causes the Zygote to purge unused native memory before fork
events. This results in a decrease in the RSS before a fork, which
decreases false sharing between parent and child, and results in less
private dirty memory in the child when allocations and deallocations
begin to dirty bookkeeping data on pages in the anon:libc_malloc
memory region.
The result of these changes is a negligible change to application
startup times, the reduction of usap32 process private dirty memory by
40 KiB and usap64 process private dirty memory by 128 KiB.  Application
RSS and private dirty memory usage (for Calendar) was reduced by 804 KiB
and 624 KiB respectively.
Test: Launched Calendar 500 times
Change-Id: I52f72a5a02182a9e2748f7f87b45665059d9891a
Merged-In: …
=> Purge unused native memory before Zygote fork events

packages/SystemUI/src/com/android/systemui/statusbar/phone/KeyguardLiftController.kt
When request pick gesture sensor, judge that if the current user does not turn on the face unlocking function, the sensor should not be Listening
Fixes: 161954958
Test: presubmit
Change-Id: I34552315049e07f123403fe693251edb460fef5d
=> Add isFaceAuthEnabledForUser checks in KeyguardLiftController

packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBar.java
Screen on animation is slow. Modern fingerprint sensor is *FAST*.
We need moar speed to deliver better user experience.
* OEMs are doing this for years.
Change-Id: I5f98259eb992b2f43872f957fcb0092412fe558c
=> Skip screen on animation when wake and unlock via biometrics
