packages/SystemUI/res/values-uk/cm_strings.xml

Change-Id: I3e954a4017eceddd77eb29627794dca8364e54b0

Automatic translation import

---

core/res/res/values-ar/strings.xml
core/res/res/values-bn-rBD/strings.xml
core/res/res/values-fa/strings.xml
core/res/res/values-gu-rIN/strings.xml
core/res/res/values-hi/strings.xml
core/res/res/values-km-rKH/strings.xml
core/res/res/values-kn-rIN/strings.xml
core/res/res/values-ko/strings.xml
core/res/res/values-lo-rLA/strings.xml
core/res/res/values-ml-rIN/strings.xml
core/res/res/values-mr-rIN/strings.xml
core/res/res/values-my-rMM/strings.xml
core/res/res/values-pa-rIN/strings.xml
core/res/res/values-pt/strings.xml
core/res/res/values-sw/strings.xml
core/res/res/values-ta-rIN/strings.xml
core/res/res/values-te-rIN/strings.xml
core/res/res/values-th/strings.xml
core/res/res/values-tl/strings.xml
core/res/res/values-ur-rPK/strings.xml
core/res/res/values-zh-rHK/strings.xml

These shouldn't be added here
Change-Id: I5373cc1ce9228c15716b408245558985a59f025f

Clean up CAF translations - second try

---

core/res/res/values-de/strings.xml

Change-Id: I058e0932f0bfe1d299e58a259a1b44a0d7f756bb

Fix permission description string for DE.

---

packages/SystemUI/res/values-de/strings.xml

Change-Id: I9a1b2345a8b101bcf27f8e92713ceb24609ec2ea

systemui: Fix DE translation for navbar buttons

---

packages/Keyguard/res/values-zh-rCN/strings.xml
packages/Keyguard/res/values/cm_strings.xml
packages/Keyguard/res/values/strings.xml

Change-Id: I7bfebdcbf47e5a562eb4b9349ce14ae8a8386c60

Keyguard: Move CAF strings to cm_strings.xml.

---

packages/SystemUI/src/com/android/systemui/settings/BrightnessController.java

Allow any user changing brightness mode,
without this only the main one is able to do that.
BUGBASH-598
Change-Id: Ib51e9a45c42837cabb1cfb0d48334165b023a827

SystemUI: Specify user while changing brightness mode

---

cmds/screencap/screencap.cpp

Change-Id: Ibd5050c79774d06f30b2f668160cdeca75f1bc58
(cherry picked from commit c1fd7edd8fc48f3308105df8cc845ec4b6652e17)
(cherry picked from commit 32339bf975f80e5610c44cad608f230c448caf7f)

ScreenCap : Add jpeg support

---

packages/SettingsLib/src/com/android/settingslib/deviceinfo/PrivateStorageInfo.java

BUGBASH-355
Change-Id: If811545e352d7e499630e11e7583d643e1510431

PrivateStorageInfo: Exclude primary physical volume total space

---

core/java/android/hardware/input/InputManager.java

This is called by an Nvidia Shield exclusive game which crashes
if the function is not found.
Change-Id: I2aea38ad8d9dab046f351e18a91b2418d8a982b2

Add stub for setCursorVisibility

---

packages/SystemUI/src/com/android/systemui/recents/views/TaskViewHeader.java

Change-Id: I8005360f932c930011d969e2913bc28efb826163

SystemUI: Fix title text clipping when task lock button is visible

---

packages/SystemUI/src/com/android/systemui/volume/VolumeDialogControllerImpl.java

Change-Id: I1acef6923744abf782360f83e06b90d873ba20a9

SystemUI: Use Java range for volume tone tone generator

---

services/core/java/com/android/server/StorageManagerService.java

If they are visibile to apps the media scanner will scan them.
Change-Id: Icceceafc8469b6b9d1c0e72f8425d7e38ae4a10b

storage: Set all sdcards to visible

---

packages/SystemUI/res/layout-sw600dp/nav_buttons_dpad_group_rot90.xml
packages/SystemUI/res/layout/nav_buttons_dpad_group.xml
packages/SystemUI/res/layout/nav_buttons_dpad_group_rot90.xml
packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarView.java

* Fixes issue where input events would be sent
while dpad_group view was set to be invisible.
Change-Id: Ie802e9c8157505a2ad706332f0b2fe715caf428c

SystemUI: Fix navigation bar arrows visibility handling

---

packages/SettingsProvider/res/values/lineage_defaults.xml
packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java

Change-Id: I934331ae8c91a6a11e7a620e28ddb6db92a03040

Fix migration from pre-O for AndroidTV devices (1/2)

---

packages/SystemUI/res/values/cm_strings.xml
packages/SystemUI/res/xml/nav_bar_tuner.xml
packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarInflaterView.java

Change-Id: Id6a76c635b3d3927a2ffd8e0c2d912473d7dcde3
Signed-off-by: Jesse Chan <jc@lineageos.org>

SystemUI: add navbar button layout inversion tuning

---

packages/SystemUI/LineageManifest.xml
packages/SystemUI/res/drawable/ic_qs_reader_off.xml
packages/SystemUI/res/drawable/ic_qs_reader_on.xml
packages/SystemUI/res/values/cm_strings.xml
packages/SystemUI/res/values/config.xml
packages/SystemUI/src/com/android/systemui/qs/tileimpl/QSFactoryImpl.java
packages/SystemUI/src/com/android/systemui/qs/tiles/ReadingModeTile.java

Change-Id: I1c515cbeff0dd5a1fa0c00bc9390a66eb104c7f0

base: add reading mode tile

---

services/core/java/com/android/server/policy/PhoneWindowManager.java

* This fixes an issue where haptic feedback is used
when screen is off and home button wake is disabled.
Change-Id: I7ac4c00598cedf7f174dc99629f55dc7b74b0d2a

PhoneWindowManager: Improve home button wake haptic feedback handling

---

packages/SystemUI/res/drawable/stat_sys_data_bluetooth_connected_battery_2.xml

Change-Id: Iaea9ba2e6af150c03ef1101f0cbd6444690ee4f0

SystemUI: Fix status bar bluetooth <50% drawable

---

packages/SystemUI/src/com/android/systemui/qs/tiles/AdbOverNetworkTile.java

Change-Id: I246a0310f0015862b750aa73ed2b546ef6658c8b

SystemUI: require auth for adb wireless

---

packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBar.java

Change-Id: I4fafa2b1e342608e2690c3dda7cb06aaf88247ba

systemUi: styles: support more dark overlays

---

telecomm/java/android/telecom/Call.java
telecomm/java/android/telecom/Conference.java
telecomm/java/android/telecom/Connection.java
telecomm/java/android/telecom/ConnectionService.java

Change-Id: I4fa94d4ba68a1570d3f822be569ae124882c0e66

Proper supplementary service notification handling (1/5).

---

packages/SystemUI/src/com/android/systemui/statusbar/phone/ClockController.java

Change-Id: Ibdc4f6a707569ddb417854760cf579daca989ebb

SystemUI: Fix default clock blacklist value

---

packages/SystemUI/src/com/android/systemui/statusbar/policy/Clock.java

* Fixes ~ triple clock ~ after leaving from Google SUW.
Change-Id: I3ceea4400b3057e2b6b1f221f9074b1d451133ea

SystemUI: Initialize mClockVisibleByUser to android:visibility

---

packages/SystemUI/src/com/android/systemui/qs/tiles/DataUsageDetailView.java

Change-Id: Ieff3504baf3d13c77d06fcde87d5ac56d2586194

SystemUI: Fix Data Usage tile to match Settings

---

packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarView.java
packages/SystemUI/src/com/android/systemui/tuner/TunerServiceImpl.java

Change-Id: Ic0ca15363a624dae2f733592fe1ee12218f64db2

TunerServiceImpl: Add another key to blacklist

---

core/java/com/android/internal/view/RotationPolicy.java

Change-Id: I77301ec8c72393daa0003ca310eee07b767d4e69

RotationPolicy: Don't crash if configstore 1.1 isn't available

---

packages/SystemUI/src/com/android/systemui/qs/tiles/CellularTile.java

Change-Id: Ib41a4086e10ccba71909370549d3714815684b2f

SystemUI: Pass correct NetworkTemplate to CellularTile detail view

---

packages/SystemUI/src/com/android/systemui/biometrics/FODCircleView.java

Change-Id: Icfc46823028edb15473aee71992551ae9f7d21b8

FODCircleView: disable touch detection on screen off

---

packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarWindowView.java

Change-Id: Ic64c29eae63e96f34dc37cda355401b7e2cd2d39

SystemUI: Don't sleep on double tap below status bar

---

core/java/com/android/internal/os/BatteryStatsImpl.java

Bug: 151532393
Test: review code
Change-Id: Ifcd88b03a713f7759494ec46096459733e8789eb
Signed-off-by: wangqiuling <wangqiuling@xiaomi.com>

bugfix for noteResetVideoLocked

---

services/core/java/com/android/server/wm/DisplayPolicy.java

* Fixes system crashing after connected to Android Auto or started screen record
That was introduced on toggle navbar commit
Only register content observer if default display
Full log:
2020-03-24 21:54:54.125 1487-1580/? W/Watchdog: *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in monitor com.android.server.am.ActivityManagerService on foreground thread (android.fg), Blocked in handler on main thread (main), Blocked in handler on ui thread (android.ui), Blocked in handler on display thread (android.display), Blocked in handler on animation thread (android.anim)
2020-03-24 21:54:54.126 1487-1580/? W/Watchdog: android.fg annotated stack trace:
2020-03-24 21:54:54.127 1487-1580/? W/Watchdog:     at com.android.server.am.ActivityManagerService.monitor(ActivityManagerService.java:17558) …

DisplayPolicy: Fix watchdog when adding new display

---

packages/SystemUI/src/com/android/systemui/statusbar/NotificationMediaManager.java

* Fixes custom lockscreen wallpaper.
Change-Id: I0d65edc6c98278a1ca8a20a8906eb6b91c846af2

fixup! SystemUI: Allow to disable Lockscreen Media Art [1/3]

---

services/core/java/com/android/server/pm/Installer.java
services/core/java/com/android/server/pm/PackageManagerService.java

Test: manual, upgrade & test for profiles
Bug: 135299330
(cherry picked from commit 86b6bbd4c593aedb3c5e27995727fb2cb55c604b)
Merged-In: I39d3376fc845ec5f2b474ea6f39a3c534ed2ce69
Change-Id: I29833113f7d0806733be669cfbc6fe2b206a982f

Do not clean up ART profiles during OTAs

---

libs/hwui/surfacetexture/ImageConsumer.cpp
libs/hwui/surfacetexture/ImageConsumer.h

Bug: 138674291
Test: Ran apps with TextureView and CTS
Change-Id: Ieecf7daf160761de719356644ddaeda8f9c068e1

TextureVuew rebind GL texture, if AHB content has changed

---

packages/SystemUI/src/com/android/systemui/qs/tiles/PowerShareTile.java

* Otherwise we end up getting notification sound
every 20 seconds when using it...
Change-Id: Ia56b01f332860b64f0d2c532884e6bcaa2acfb17

SystemUI: Call setOnlyAlertOnce(true) for PowerShare notification

---

packages/PackageInstaller/src/com/android/packageinstaller/handheld/UninstallAlertDialogFragment.java

* Fixes:
- https://gitlab.com/LineageOS/issues/android/-/issues/2298
- https://issuetracker.google.com/issues/148573843
Change-Id: I5a27d6f02d17a52e1a1a2aff4fb46327ce5e6127

PackageInstaller: Fix crash when uninstalling apps with fragile data
